export const QUIZ_QUIZES_FETCH_START = 'FETCH_QUIZES_START'
export const QUIZ_QUIZES_FETCH_SUCCESS = 'FETCH_QUIZES_SUCCESS'
export const QUIZ_QUIZES_FETCH_ERROR = 'FETCH_QUIZES_ERROR'
export const QUIZ_FETCH_SUCCESS = 'FETCH_QUIZ_SUCCESS'
export const QUIZ_SET_STATE = 'QUIZ_SET_STATE'
export const QUIZ_FINISH = 'QUIZ_FINISH'
export const QUIZ_NEXT_QUESTION = 'QUIZ_NEXT_QUESTION'
export const QUIZ_RETRY_TEST = 'QUIZ_RETRY_TEST'


export const CREATE_QUIZ_QUESTION = 'CREATE_QUIZ_QUESTION'
export const CREATE_QUIZ_RESET = 'CREATE_QUIZ_RESET'
export const CREATE_QUIZ_FETCH_START = 'CREATE_QUIZ_FETCH_START'
export const CREATE_QUIZ_FETCH_SUCCESS = 'CREATE_QUIZ_FETCH_SUCCESS'
export const CREATE_QUIZ_FETCH_ERROR = 'CREATE_QUIZ_FETCH_SUCCESS'


export const AUTH_LOGOUT = 'AUTH_LOGOUT'
export const AUTH_FETCH_START = 'AUTH_FETCH_START'
export const AUTH_FETCH_SUCCESS = 'AUTH_FETCH_SUCCESS'
export const AUTH_FETCH_ERROR = 'AUTH_FETCH_ERROR'